apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: "azure-{{ include "app.name" . }}-{{ .Values.csisecrets.vaultname }}"
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.csisecrets.clientId }}"
    keyvaultName: "{{ .Values.csisecrets.vaultname }}"
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: {{ .Values.appgw.rootCertificateName }}
          objectAlias: identity.p12
          objectType: secret
          objectFormat: PFX
          objectEncoding: base64
    tenantId: "{{ .Values.csisecrets.tenantId }}" # the tenant ID of the KeyVault
