apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.name" . }}-service
  labels:
    app: {{ include "app.name" . }}
spec:
  selector:
    app: {{ include "app.name" . }}
  ports:
    - name: https
      protocol: TCP
      port: 8443
      targetPort: 8080