name: Deploy AKS-Construction

on:
  workflow_dispatch:

jobs:
  reusable_workflow_job:
    uses: Azure/AKS-Construction/.github/workflows/AKSC_Deploy.yml@main
    with:
      templateVersion: 0.8.7
      rg: az-k8s-c4vz-rg
      resourceName: az-k8s-c4vz
      templateParams: "resourceName=az-k8s-c4vz agentCount=2 upgradeChannel=stable JustUseSystemPool=true custom_vnet=true bastion=true enable_aad=true AksDisableLocalAccounts=true enableAzureRBAC=true adminPrincipalId=_USER_OBJECT_ID_ registries_sku=Premium acrPushRolePrincipalId=_USER_OBJECT_ID_ imageNames="[\"k8s.gcr.io/external-dns/external-dns:v0.11.0\"]" azureFirewalls=true certManagerFW=true privateLinks=true kvIPAllowlist="[\"5.67.72.204/32\"]" omsagent=true retentionInDays=30 networkPolicy=azure azurepolicy=audit enablePrivateCluster=true dnsZoneId=/subscriptions/95efa97a-9b5d-4f74-9f75-a3396e23344d/resourceGroups/kh-common/providers/Microsoft.Network/dnszones/labhome.biz ingressApplicationGateway=true appGWcount=0 appGWsku=WAF_v2 appGWmaxCount=10 appgwKVIntegration=true azureKeyvaultSecretsProvider=true createKV=true kvOfficerRolePrincipalId=_USER_OBJECT_ID_ acrPrivatePool=true"
      postScriptInvokeCommand: true
      postScriptParams: "dnsZoneId=/subscriptions/95efa97a-9b5d-4f74-9f75-a3396e23344d/resourceGroups/kh-common/providers/Microsoft.Network/dnszones/labhome.biz,ingress=appgw,certEmail=kforce1234@gmail.com,acrName=$(az acr list -g az-k8s-c4vz-rg --query [0].name -o tsv)"
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      USER_OBJECT_ID: ${{ secrets.USER_OBJECT_ID }}
