# This is a 'REUSABLE WORKFLOW' which is called from another workflow to install the application

on:
  workflow_call:
    inputs:
      RG:
        required: true
        type: string
      AKSNAME:
        required: true
        type: string
      DNSDOMAIN:
        required: true
        type: string
      DNSRG:
        required: true
        type: string
      DNSRECORDNAME:
        required: true
        type: string
      AKVNAME:
        required: true
        type: string
      AGNAME:
        required: true
        type: string
      APPNAME:
        default: "openjdk-kvssl"
        required: true
        type: string
      FRONTENDCERTTYPE:
        default: "certmanager-staging"
        required: false
        type: string
        #type: choice
        ##options:
        #- certmanager-staging
        #- certmanager-production
        #- appgw-selfsigned
      HELMCERTMANAGERISSUERURI:
        default: "helm/Az-CertManagerIssuer-0.3.0.tgz"
        required: false
        type: string
      HELMEXTERNALDNSURI:
        default: "helm/externaldns-0.2.0.tgz"
        required: false
        type: string
      HELMAPPURI:
        default: "helm/openjdk-demo-3.1.0.tgz"
        required: false
        type: string
      CERTMANAGERVERSION:
        default: "v1.5.3"
        required: false
        type: string
      CERTMANAGEREMAIL:
        default: ""
        required: false
        type: string
      VERIFYURLTIMEOUTMINS:
        default: 3
        required: false
        type: number
      FORCEHELMCLEANINSTALL:
        description: 'If App is already installed, remove explictly before install'
        type: boolean
        default: false
        required: false
      UNINSTALLAFTERVERIFY:
        description: 'Uninstall app after tests  [yes|no]'
        type: boolean
        default: false
        required: false
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  App_Create:
    runs-on: ubuntu-latest
    concurrency: "Ag-${{ inputs.AGNAME}}" #AppGateway doesn't like concurrent updates
    env: #We create the environment variables here instead of at the step level for clarity and to ensure consistency with the WizardUI
      APPNAME: "${{ inputs.APPNAME }}"
      AKVNAME: "${{ inputs.AKVNAME }}"
      CERTNAME: "${{ inputs.APPNAME }}"
      RG: "${{ inputs.RG }}"
      KVNAME: "${{ inputs.AKVNAME }}"
      AGNAME: "${{ inputs.AGNAME }}"
      AKSNAME: "${{ inputs.AKSNAME }}"
      DNSDOMAIN: "${{ inputs.DNSDOMAIN }}"
      DNSRG: "${{ inputs.DNSRG }}"
      DNSRECORDNAME: "${{ inputs.DNSRECORDNAME }}"
      NAMESP: "default"
      APPURL: "https://${{ inputs.APPNAME }}.${{ inputs.DNSDOMAIN }}"
      kubeloginversion: 'v0.0.10'

    steps:
      #- uses: actions/checkout@v2  #Checks out the files from the Calling workflows repository, cannot use it. We need to be more specific in our repo checkout

      - uses: actions/checkout@v2
        name: Checkout repo for dependant scripts/
        with:
          repository: azure-samples/java-aks-keyvault-tls
          ref: 'gb-workflow' #TODO:change this to a specific release tag before PR
        
      - name: Job parameter inspection
        run: |
          echo "RG is ${{ inputs.RG }}"
          echo "AKS name is ${{ inputs.AKSNAME }}"
          echo "FrontendCert type is ${{ inputs.FRONTENDCERTTYPE }}"
          echo "CertManager version is ${{ inputs.CERTMANAGERVERSION }}"

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: false
          environment: azurecloud
          allow-no-subscriptions: false

      - name: Create self signed certs in Key Vault
        run: sh scripts/akv-create-certs.sh

      - name: Create Root Cert references in AppGw
        id: AppGwRootCert
        run: sh scripts/agw-create-root-cert.sh

      - name: Create FrontEnd Cert references in AppGw
        if: inputs.FRONTENDCERTTYPE == 'appgw-selfsigned'
        run: sh scripts/agw-create-ssl-cert.sh

      - name: Confirm certificates registered in AppGw
        run: |
          az network application-gateway ssl-cert list -g $RG --gateway-name $AGNAME --query "[].name"
          az network application-gateway root-cert list -g $RG --gateway-name $AGNAME --query "[].name"

      - name: AKS Connect
        run: sh scripts/aks-connect.sh

      - name: Observe Existing DNSConfig
        run: az network dns record-set list -g $DNSRG -z $DNSDOMAIN --query "[?name=='$DNSRECORDNAME'][{type:type,fqdn:fqdn,aRecords:aRecords,txtRecords:txtRecords}]"

      - name: Check if App Helm Chart already installed
        if: inputs.FORCEHELMCLEANINSTALL == true
        run: |
          APPINSTALLED=$(helm list --filter ^$APPNAME$ --short)
          if [ -z "$APPINSTALLED" ]
          then
                echo "App not installed"
          else
                echo "App already installed, forcing uninstall"
                helm list --short
                helm uninstall $APPNAME
                sleep 1m
          fi

      - name: Install Cert Manager
        if: startsWith(inputs.FRONTENDCERTTYPE, 'certmanager' )
        env:
          CERTMANAGERURI: "https://github.com/jetstack/cert-manager/releases/download/${{ inputs.CERTMANAGERVERSION }}/cert-manager.yaml"
          EMAILAD: "${{ inputs.CERTMANAGEREMAIL }}"
        run: |
          echo "Installing Cert Manager ${{ inputs.CERTMANAGERVERSION }}"
          kubectl apply -f $CERTMANAGERURI
          sleep 1m

          echo "Installing Cert Manager ClusterIssuer"
          echo "Email Address for Lets Encrypt: $EMAILAD"
          helm upgrade --install smokecertissuer ${{ inputs.HELMCERTMANAGERISSUERURI }} --set email=$EMAILAD
          sleep 1m

      - name: Verify Cert Manager ClusterIssuer
        if: startsWith(inputs.FRONTENDCERTTYPE, 'certmanager' )
        run: |
          case "${{ inputs.FRONTENDCERTTYPE }}" in
             "certmanager-staging") CERTSOURCE="letsEncrypt"; LEISSUER="letsencrypt-staging" ;;
             "certmanager-production") CERTSOURCE="letsEncrypt" LEISSUER="letsencrypt-production" ;;
          esac

          kubectl describe clusterissuer $LEISSUER

      - name: Create azure-config secret and install externaldns
        run: sh scripts/externaldns-create-k8s-secret.sh

      - name: Install the Java sample app
        run: |
          KVNAMELOWER=${AKVNAME,,}
          KVTENANT=$(az account show --query tenantId -o tsv)
          DNSNAME=${APPNAME}.${DNSDOMAIN}

          case "${{ inputs.FRONTENDCERTTYPE }}" in
             "appgw-selfsigned") CERTSOURCE="appGw"; LEISSUER="" ;;
             "certmanager-staging") CERTSOURCE="letsEncrypt"; LEISSUER="letsencrypt-staging" ;;
             "certmanager-production") CERTSOURCE="letsEncrypt" LEISSUER="letsencrypt-production" ;;
          esac

          echo 'Get the identity created from the KeyVaultSecret Addon'
          export CSISECRET_CLIENTID=$(az aks show -g $RG --name $AKSNAME --query addonProfiles.azureKeyvaultSecretsProvider.identity.clientId -o tsv)
          echo $CSISECRET_CLIENTID

          helm upgrade --install $APPNAME ${{ inputs.HELMAPPURI }} --set nameOverride="${APPNAME}",frontendCertificateSource="${CERTSOURCE}",csisecrets.vaultname="${KVNAMELOWER}",csisecrets.tenantId="${KVTENANT}",csisecrets.clientId="${CSISECRET_CLIENTID}",dnsname="${DNSNAME}",appgw.frontendCertificateName="${APPNAME}-fe",appgw.rootCertificateName="${APPNAME}",letsEncrypt.issuer="${LEISSUER}",letsEncrypt.secretname="${APPNAME}-tls" --dry-run
          helm upgrade --install $APPNAME ${{ inputs.HELMAPPURI }} --set nameOverride="${APPNAME}",frontendCertificateSource="${CERTSOURCE}",csisecrets.vaultname="${KVNAMELOWER}",csisecrets.tenantId="${KVTENANT}",csisecrets.clientId="${CSISECRET_CLIENTID}",dnsname="${DNSNAME}",appgw.frontendCertificateName="${APPNAME}-fe",appgw.rootCertificateName="${APPNAME}",letsEncrypt.issuer="${LEISSUER},letsEncrypt.secretname="${APPNAME}-tls""

      - name: Wait for External DNS config
        run: |
          counter=1
          while [ $counter -le 10 ]
          do
            dnsrecords=$(az network dns record-set list -g $DNSRG -z $DNSDOMAIN --query "[?name=='$DNSRECORDNAME'][{type:type,fqdn:fqdn,aRecords:aRecords,txtRecords:txtRecords}]")

            if [ "$dnsrecords" != "[]" ]
            then
                  echo "DNS Records have been created [$counter] [$(date +"%T")]"
                  echo $dnsrecords
                  break 2
            fi

            echo "ExternalDNS has not created Azure DNS Records yet [$counter] [$(date +"%T")]"

            ((counter++))
            sleep 10s
          done

          if [ "$dnsrecords" == "[]" ]
          then
            echo "ExternalDNS has not created Azure DNS Records in a timely fashion, suggest you examine the ExternalDNS pod logs with; kubectl logs -l app=externaldns"
            kubectl logs -l app=externaldns
            exit 1
          fi

      - name: Wait for Cert Manager to issue certificate
        if: startsWith(inputs.FRONTENDCERTTYPE, 'certmanager' )
        env:
          SECRETNAME: "${{ inputs.APPNAME }}-tls"
        run: |
          counter=1
          while [ $counter -le 10 ]
          do
            kubectl get po

            secret=$(kubectl get secret $SECRETNAME --ignore-not-found)
            kubectl get secret $SECRETNAME --ignore-not-found

            if [ ! -z "$secret" ]
            then
                  echo "Secret $SECRETNAME has been created"
                  break 2
            fi

            ((counter++))
            sleep 10s
          done

          if [ -z "$secret" ]
          then
            echo "CertManager ClusterIssuer has not created the certificate secret in a timely fashion, suggest you examine the logs"
            kubectl get pods
            exit 1
          fi

      - name: Verify Java App is reachable
        timeout-minutes: 5
        run: |
          echo "curl $URLTOHIT [$(date +"%T")]"
          curlcommand="curl --connect-timeout 2 --retry 25 --retry-delay 20 --no-keepalive --no-tcp-nodelay -X GET --insecure --write-out %{http_code} --silent --fail --output /dev/null $APPURL -v --trace-time"
          respcode=$($curlcommand || sleep 1m; $curlcommand)

          echo $respcode

          curl --insecure $URLTOHIT

      - name: Verify Frontend Certificate
        run: |
          curl --insecure -vvI $APPURL 2>&1 | awk 'BEGIN { cert=0 } /^\* SSL connection/ { cert=1 } /^\*/ { if (cert) print }'

      - name: Cleanup app
        if: inputs.UNINSTALLAFTERVERIFY
        run: helm uninstall $APPNAME
